#!/usr/bin/env bash

# Set up autograder files

cd /autograder/test

git checkout main

git config user.name 'Autograder'
git config user.email '<>'

git pull

cp /autograder/submission/calculator.py /autograder/source/calculator.py

cd /autograder/source

python3 run_tests.py

ID=$(jq '.users[0].id' /autograder/submission_metadata.json)

TIMESTAMP=$(jq '.created_at[:-6]' /autograder/submission_metadata.json)

cd /autograder/test

git checkout submissions

git pull

rm -r /autograder/test/${ID}
cp -R /autograder/submission/ /autograder/test/${ID}

echo ${TIMESTAMP} > /autograder/test/${ID}/timestamp.txt

git add /autograder/test/${ID}
git push

git switch main

echo ${ID}
echo ${TIMESTAMP}
