#!/usr/bin/env bash

# Pull autograder changes, then run full_autograder

cd /autograder/grading

git config user.name 'Autograder'
git config user.email '<>'

git pull

cd /autograder/grading/my_autograder
./full_autograder.sh
